### ISSUE TITLE
Application crashing on background sync

### ISSUE THREAD

**Issue by benbense** [rgb-master-team/RGBMaster#11]
If you start syncing (on any mode) and then exit the app without stopping the sync, the sync continue although you can't see the app running (except in task manager) and when trying to re-open the app it instantly crashes.

**Comment by deankevorkian** [comment]
Fixed with [8ba92eeb8110cea404c0a1f169ccb93035a42d03](https://github.com/rgb-master-team/RGBMaster/commit/8ba92eeb8110cea404c0a1f169ccb93035a42d03).
