### ISSUE TITLE
Correcly manage state & Modify UI to stop abusing ObservableCollection and start using DependencyProperty

### ISSUE THREAD

**Issue by deankevorkian** [rgb-master-team/RGBMaster#13]
Due to lack of experience in UI, Xaml Islands, WPF & UWP, we'd like help with replacing certain areas in our state where we abuse ObservableCollection to get auto, free rendering of parts of our UI when something happens - devices are discovered, providers are being refreshed, etc.

We must start using DependencyProperty for better performance + the ability to propagate changes and trigger re-rendering when we change things.

For example - we want to uncheck a device if we failed to connect to it..

Any help appreciated.

**Comment by BrandonGillis** [comment]
What about using something like chromely for doing the UI ? That could allow to make a more advanced UI with less trouble than WPF

**Comment by deankevorkian** [comment]
We did consider this at the beginning - using Electron, WPF with CefSharp, etc.... but we wanted to stay closer to native to ensure we don't have situations where we can't access certain things without having to build bridges between technologies. We use WPF for the app initialization but on top of it there's a Xaml Islands bridge that allows us to write the app in Windows 10's Fluent design (with WinUI on top of UWP).
I'd feel more comfortable using a web platform for the UI if the app had a "client-server" architecture where the client's written in web technologies and the server receives orders (connection and manipulations of devices).
We can still do this but in a much later release probably. I don't think the overhead is worth it for such app.
So if we still use one app to do the UI and the manipulations too I'd want something close to native, although I'm experienced in Angular
