### ISSUE TITLE
[feature] Sync razer chroma with yeelight

### ISSUE THREAD

**Issue by BrandonGillis** [rgb-master-team/RGBMaster#14]
This feature is about syncing current color of razer chroma such as spectrum cycling, to yeelight devices.

**Comment by deankevorkian** [comment]
I'd like to support such a thing - and it was one of the original things I wanted before I started this app.
I wanted the colors to be controlled via Chroma (to allow having their special effects - spectrum, music and all of that) - but their SDK doesn't allow receiving the color from Chroma or a specific device.
You can only set the color via Chroma SDK but you cannot receive a stream of changes from them, unless you join their [Connected Devices Program](https://developer.razer.com/connected-devices/).
If and when they allow us to subscribe to their color stream or connect to it somehow we would support this.
