### ISSUE TITLE
Yeelight connectivity issues when using more than one network adapter (physical/virtual)

### ISSUE THREAD

**Issue by tojatomasz** [rgb-master-team/RGBMaster#19]
Hello,

### **Background:**
Yesterday i upgraded my Win10 from build 1909 to 202H and suddently RGBMaster stopped working (unable to establish connection with yeelight)
At first i suspected that it has something to do with Win10 update but then it was confirmed from somebody else that it works on newest Win10 build
Next suspect was Windows Firewall, i tried disabling it, restoring to default settings etc.. still nothing
Then @deankevorkian told me that it could be blocked ports or something (generally speaking: problems with network)
It gave me idea to hook up Wireshark and i found what is the problem..

### **Issue:**
When there's more than one network adapter (like in attached picture) the RGBMaster is picking the wrong one
![explorer_swtl9bJouh](https://user-images.githubusercontent.com/3491056/102137000-7375a280-3e5a-11eb-8fda-95fa487c4a02.png)

**When i disable all adapters except the correct one it works flawlessly**

Btw: I upgraded W10 to use WSL2, and it seems that this feature installed new network adapter on my PC

**Comment by deankevorkian** [comment]
Resolved on version 2.4 - and thank you for the amazing contribution!
