### ISSUE TITLE
Chroma install

### ISSUE THREAD

**Issue by mclaudiopt** [rgb-master-team/RGBMaster#3]
Hello
i have chroma speakers and wish to sync with yeelight...
how can i install this?
thanks

**Comment by deankevorkian** [comment]
Hi, you can download the latest release from [here](https://github.com/deankevorkian/RGBMaster/releases/tag/1.1).

Just unzip and run RGBMaster.exe. Make sure you you allow the software Internet access when your firewall prompt comes up. You may have issues running the app because, as of now, the app may not work if some SDKs are missing. I'm going to fix this today and release a new version.

See if it works and let me know!
also, make sure you install Razer Synapse 3. This is in order for Chroma devices to work.

**Comment by mclaudiopt** [comment]
hi. i unzipped but when choose sync it just closes. i dont have anything installed...only Synapse.
i wish to connect to yeelight
in the future with SHELLY RGB wich is a great platform
what should be my next steps?

**Comment by deankevorkian** [comment]
I'd be happy to support Shelly RGB! But I'm gonna need some help testing it since I don't have a device or a way to simulate one.

I'll put a new version tonight that allows you to choose which providers you connect to (chroma, yeelight, logitech etc.). Currently, it tries to connect to all of them, so if one of them is missing it crashes. This is just a UI matter, nothing more.

Until tonight, do you have visual studio? If so, I can instruct you where to modify it so it doesn't crash for you.

**Comment by mclaudiopt** [comment]
i am installing it now
SHELLY IS GREAT . it can work with node red.js mqtt or REST command
https://shelly-api-docs.shelly.cloud/#shelly-rgbw2-color
https://shelly-api-docs.shelly.cloud/#common-http-api

**Comment by mclaudiopt** [comment]
what is needed?

**Comment by deankevorkian** [comment]
Just took a look in Shelly's API - it does look great! We'll definitely implement it.

If you want to debug the program you'll need to select .NET Desktop Environment + universal Windows platform development (because we're migrating from WPF to UWP in the near future).

Let me know when you're done

**Comment by mclaudiopt** [comment]
ok ! i will install it...but on the afternoon i have some meetings, if i do not give feedback i will give tonight
ok?

**Comment by deankevorkian** [comment]
Sure! Appreciate the feedback and support ❤️

**Comment by mclaudiopt** [comment]
ok now again at home...i can test now

**Comment by deankevorkian** [comment]
In `MainWindow.xaml.cs`, try to modify GetProviders so it returns on Yeelight provider & RazerChroma providers:

`return new List<Provider>() { new YeelightProvider(), new RazerChromaProvider() };`

**Comment by mclaudiopt** [comment]
i dont have mainwindow...
![image](https://user-images.githubusercontent.com/48178294/83564344-7808e800-a514-11ea-841b-fed9adf683b7.png)

**Comment by deankevorkian** [comment]
You're looking at the release instead of the source code itself.
You can clone this repository [or download the source code from this link](https://github.com/deankevorkian/RGBMaster/archive/master.zip).

Unzip it, then open `RGBMaster.sln`

**Comment by mclaudiopt** [comment]
done
how do i compile it now?


namespace chroma_yeelight
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : MetroWindow
    {
        private IEnumerable<Provider> providers;
        private IEnumerable<Device> selectedDevices;
        private IEffect selectedEffect;

        public MainWindow()
        {
            InitializeComponent();

            if (Environment.GetCommandLineArgs().Any(x => x == "--start-immediate"))
            {
                Task.Run(() => StartSyncing());
            }

            this.providers = GetProviders();
        }

        private async void StartSyncBtn_Click(object sender, RoutedEventArgs e)
        {
            switch (EffectFlipView.SelectedIndex)
            {
                case 0:
                    selectedEffect = new MusicEffect();
                        break;
                case 1:
                    selectedEffect = new DominantDisplayColorEffect();
                    break;
                default:
                    break;
            }

            await StartSyncing();
        }

        private async Task StartSyncing()
        {
            RegisterProviders();
            Dictionary<Provider, IEnumerable<Device>> providerToDevices = await DiscoverProvidersDevices();

            // GetSelectedDevices from the user or something.. and then:
            selectedDevices = GetSelectedDevices(providerToDevices);
            await ConnectToSelectedDevices();

            //selectedEffect = new MusicEffect();
            //selectedEffect = new MusicEffect();

            try
            {
                await selectedEffect.Start(selectedDevices);
            }
            catch (Exception ex)
            {
                throw new AudioCaptureAccessDeniedException(ex);
            }
        }

        private async Task ConnectToSelectedDevices()
        {
            foreach (var device in selectedDevices)
            {
                await device.Connect();
            }
        }

        private IEnumerable<Device> GetSelectedDevices(Dictionary<Provider, IEnumerable<Device>> providerToDevices)
        {
            return providerToDevices.Values.SelectMany(devices => devices).ToList();
        }

        private async Task<Dictionary<Provider, IEnumerable<Device>>> DiscoverProvidersDevices()
        {
            Dictionary<Provider, IEnumerable<Device>> providerToDevices = new Dictionary<Provider, IEnumerable<Device>>();
            foreach (var provider in providers)
            {
                IEnumerable<Device> devices;
                try
                {
                    devices = await provider.Discover();
                }
                catch (Exception ex)
                {
                    throw new DiscoveryFailedException(provider, ex);
                }

                if (providerToDevices.ContainsKey(provider))
                {
                    throw new DuplicateProvidersException(provider, null);
                }

                providerToDevices.Add(provider, devices);
            }

            return providerToDevices;
        }

        private async void RegisterProviders()
        {
            foreach (var provider in providers)
            {
                try
                {
                    await provider.Register();
                }
                catch (Exception ex)
                {
                    throw new ProviderRegistrationFailedException(provider, ex);
                }
            }
        }

        private IEnumerable<Provider> GetProviders()
        {
            return new List<Provider>() { new YeelightProvider(), new RazerChromaProvider() };
		}

        private async void StopSyncingBtn_Click(object sender, RoutedEventArgs e)
        {
            await selectedEffect.Stop();

            foreach (var device in selectedDevices)
            {
                await device.Disconnect();
            }

            foreach (var provider in this.providers)
            {
                await provider.Unregister();
            }
        }

        private void EffectFlipView_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            var flipView = (FlipView)sender;

            switch (flipView.SelectedIndex)
            {
                case 0:
                    flipView.BannerText = "Music Mode that should be fucking binded by now";
                    break;
                case 1:
                    flipView.BannerText = "Cursor mode which should be fucking renamed (or let its settings change) and also be fucking binded by now!";
                    break;
                default:
                    break;
            }
        }
    }
}

**Comment by mclaudiopt** [comment]
```


namespace chroma_yeelight
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : MetroWindow
    {
        private IEnumerable<Provider> providers;
        private IEnumerable<Device> selectedDevices;
        private IEffect selectedEffect;

        public MainWindow()
        {
            InitializeComponent();

            if (Environment.GetCommandLineArgs().Any(x => x == "--start-immediate"))
            {
                Task.Run(() => StartSyncing());
            }

            this.providers = GetProviders();
        }

        private async void StartSyncBtn_Click(object sender, RoutedEventArgs e)
        {
            switch (EffectFlipView.SelectedIndex)
            {
                case 0:
                    selectedEffect = new MusicEffect();
                        break;
                case 1:
                    selectedEffect = new DominantDisplayColorEffect();
                    break;
                default:
                    break;
            }

            await StartSyncing();
        }

        private async Task StartSyncing()
        {
            RegisterProviders();
            Dictionary<Provider, IEnumerable<Device>> providerToDevices = await DiscoverProvidersDevices();

            // GetSelectedDevices from the user or something.. and then:
            selectedDevices = GetSelectedDevices(providerToDevices);
            await ConnectToSelectedDevices();

            //selectedEffect = new MusicEffect();
            //selectedEffect = new MusicEffect();

            try
            {
                await selectedEffect.Start(selectedDevices);
            }
            catch (Exception ex)
            {
                throw new AudioCaptureAccessDeniedException(ex);
            }
        }

        private async Task ConnectToSelectedDevices()
        {
            foreach (var device in selectedDevices)
            {
                await device.Connect();
            }
        }

        private IEnumerable<Device> GetSelectedDevices(Dictionary<Provider, IEnumerable<Device>> providerToDevices)
        {
            return providerToDevices.Values.SelectMany(devices => devices).ToList();
        }

        private async Task<Dictionary<Provider, IEnumerable<Device>>> DiscoverProvidersDevices()
        {
            Dictionary<Provider, IEnumerable<Device>> providerToDevices = new Dictionary<Provider, IEnumerable<Device>>();
            foreach (var provider in providers)
            {
                IEnumerable<Device> devices;
                try
                {
                    devices = await provider.Discover();
                }
                catch (Exception ex)
                {
                    throw new DiscoveryFailedException(provider, ex);
                }

                if (providerToDevices.ContainsKey(provider))
                {
                    throw new DuplicateProvidersException(provider, null);
                }

                providerToDevices.Add(provider, devices);
            }

            return providerToDevices;
        }

        private async void RegisterProviders()
        {
            foreach (var provider in providers)
            {
                try
                {
                    await provider.Register();
                }
                catch (Exception ex)
                {
                    throw new ProviderRegistrationFailedException(provider, ex);
                }
            }
        }

        private IEnumerable<Provider> GetProviders()
        {
            return new List<Provider>() { new YeelightProvider(), new RazerChromaProvider() };
		}

        private async void StopSyncingBtn_Click(object sender, RoutedEventArgs e)
        {
            await selectedEffect.Stop();

            foreach (var device in selectedDevices)
            {
                await device.Disconnect();
            }

            foreach (var provider in this.providers)
            {
                await provider.Unregister();
            }
        }

        private void EffectFlipView_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            var flipView = (FlipView)sender;

            switch (flipView.SelectedIndex)
            {
                case 0:
                    flipView.BannerText = "Music Mode that should be fucking binded by now";
                    break;
                case 1:
                    flipView.BannerText = "Cursor mode which should be fucking renamed (or let its settings change) and also be fucking binded by now!";
                    break;
                default:
                    break;
            }
        }
    }
}
```

**Comment by mclaudiopt** [comment]
well i think i will just wait for the new release :-^)
![image](https://user-images.githubusercontent.com/48178294/83567129-0717ff00-a519-11ea-80e5-26661c7924a8.png)

**Comment by benbense** [comment]
First, check your firewall settings, and give permissions to the program (or maybe try to turn it off just to check).
In any case, we are working on a new version that will let you choose specific provides, it will be out very soon, i'd rather keep you waiting for a simpler version and not get messy with debugging the code.

**Comment by mclaudiopt** [comment]
yes i will wait

**Comment by mclaudiopt** [comment]
hi there
do u think it will be available today? thanmks

**Comment by benbense** [comment]
We will push the new version later this day.

**Comment by benbense** [comment]
Hey, we just put a new version that allows to select specific providers of devices, discover devices of these providers, and select which devices to sync.
You have to do this via the "Devices" tab on the app, before you click "start syncing".
So you have to choose the providers you want, discover devices, choose devices to sync and only then start syncing.

**Comment by mclaudiopt** [comment]
hi . thanks for the update
it apparently discovers but does not put IP or something
it let me choose it but when i sync nothing happens
![image](https://user-images.githubusercontent.com/48178294/83646048-12b40600-a5ab-11ea-97c0-8adda19b9165.png)

**Comment by benbense** [comment]
In some devices of yeelight, the name is not present (specific models). @deankevorkian is looking into it, maybe we'll present the IP address instead of the name.

When you select the empty line on the right side (the checkbox with no name), and then go to Effects and hit "Start Syncing" - nothing happens?

**Comment by mclaudiopt** [comment]
hi
yes nothing happens
we can make teamviewer if you prefer

**Comment by mclaudiopt** [comment]
well started again and now works...but if i also choose razer then it closes the program

**Comment by mclaudiopt** [comment]
hi
yes i have synapse 3 beta

**Comment by deankevorkian** [comment]
We're in the middle of an ongoing rewrite in WPF with UWP controls (with XAML Islands) which will release extremely soon and is going to be a lot more stable.

We created a Discord channel, you can join there from the project's README and we can talk there to solve the issues with chroma together.

**Comment by mclaudiopt** [comment]
i will join
what is the channel?

**Comment by benbense** [comment]
Click the link:
https://discord.gg/pQyqMz
Join the general chat channel

**Comment by benbense** [comment]
Eventually, Razer Synapse wasn't installed with the Studio expansion. 
After fixing that issue the program started working.
Either way little bugs that appeared (color spectrum, color flickering etc.) will be fixed in the upcoming versions.
