### ISSUE TITLE
WassapiLoopbackCapture crashes the app when an equalizer is present

### ISSUE THREAD

**Issue by benbense** [rgb-master-team/RGBMaster#5]
When using the music sync effect, we make a use of `WassapiLoopbackCapture`.
However, when equalizers run on the host (or drivers that interfere with the system's output), some `COMException`s are present.
We need to track down any exception that can occur and check why it happens.

We can use Razer Surround as a test case.

**Comment by benbense** [comment]
As we are refactoring the code and eventually using .NET Core, `WassapiLoopbackCapture` is not supported by that platform as for now.
Starting to implement `ASIO` for now.

**Comment by deankevorkian** [comment]
ASIO doesn't fit us well and kind of forces our clients to preinstall an ASIO4ALL client in case they don't have an ASIO driver support... So we're back to WasapiLoopbackCapture which is possible in our current structure.
