### ISSUE TITLE
instal issue  error code: 0x800B0109

### ISSUE THREAD

**Issue by fronxie** [rgb-master-team/RGBMaster#50]
Hi!

Can anyone help me of this error?
Thanks!
![error](https://user-images.githubusercontent.com/90519834/132953580-fc5c95ae-6201-4b75-a131-31bc7a0e8887.png)

**Comment by deankevorkian** [comment]
I believe this is related to #47 . For the mean time I'll keep this open and comment when it's fixed so I can ensure it deals with your issue

**Comment by deankevorkian** [comment]
Fixed with #53 .
